---
# This role installs httpd

- name: Install http
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - git
   
- name: Configure SELinux to allow haproxy to connect any TCP port
  seboolean:
    name: haproxy_connect_any
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: http service state
  service: name=httpd state=started enabled=yes
